language: r
cache: packages
pandoc_version: 2.9.2.1

addons:
  apt:
    packages:
    - ghostscript

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh

travis encrypt GITHUB_PAT=11AADHNZY0JNBKOTQto0lr_AOEBztEneuHbk1qikIiodi841tCOMLcO2EEyqkCme8k3DFCO2CAoQJE8iTs


# configure your name and email if you have not done so
git config --global user.email "vivianachius@umass.edu"
git config --global user.name "Viviana Wu"

# clone the repository to the book-output directory
git clone -b gh-pages \
  https://${GITHUB_PAT}@github.com/${TRAVIS_REPO_SLUG}.git \
  book-output
cd book-output
git rm -rf *
cp -r ../_book/* ./
git add --all *
git commit -m "Update the book"
git push -q origin gh-pages
