language: r
cache: packages
pandoc_version: 2.9.2.1

addons:
  apt:
    packages:
    - ghostscript

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh

travis encrypt GITHUB_PAT=11AADHNZY0JNBKOTQto0lr_AOEBztEneuHbk1qikIiodi841tCOMLcO2EEyqkCme8k3DFCO2CAoQJE8iTs
